web/router.ex
defmodule Vutuv.Router do
  use Vutuv.Web, :router
  alias Vutuv.Plug, as: Plug

  if Mix.env == :dev do
    forward "/sent_emails", Bamboo.EmailPreviewPlug
  end

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    #plug Vutuv.Plug.ManageCookies
    plug :put_secure_browser_headers
    plug Plug.ConfigureSession, repo: Vutuv.Repo
    plug Plug.Locale
  end

  pipeline :user_pipe do
    plug Plug.UserResolveSlug
    plug Plug.EnsureValidated
  end

  pipeline :api do
    plug :accepts, ["json-api"]
    plug Plug.PutAPIHeaders
    plug Plug.Locale
  end

  pipeline :render_404 do
    plug Plug.All404
  end

  scope "/", Vutuv do
    pipe_through :browser # Use the default browser stack


    resources "/tags", TagController, only: [:index, :show], param: "slug"

    get "/", PageController, :index
    get "/impressum", PageController, :impressum
    get "/listings/most_followed_users", PageController, :most_followed_users
    get "/new_registration", PageController, :redirect_index
    post "/new_registration", PageController, :new_registration

    # TODO: delete the following route entries
    resources "/memberships", MembershipController, only: [:create, :delete]
    resources "/connections", ConnectionController, only: [:create, :delete] do
      resources "/memberships", MembershipController, only: [:create, :delete]
    end

    resources "/search_queries", SearchQueryController, only: [:create, :new, :show]

    resources "/users", UserController, param: "slug" do
      pipe_through :user_pipe
      resources "/emails", EmailController
      resources "/slugs", SlugController, only: [:index, :new, :create, :show, :update]
      resources "/groups", GroupController
      resources "/followers", FollowerController, only: [:index]
      resources "/followees", FolloweeController, only: [:index]
      resources "/user_tag_endorsements", UserTagEndorsementController, only: [:create, :delete], as: :tag_endorsement
      resources "/phone_numbers", PhoneNumberController
      resources "/dates", DateController
      resources "/links", UrlController
      resources "/social_media_accounts", SocialMediaAccountController
      resources "/work_experiences", WorkExperienceController
      resources "/addresses", AddressController
      resources "/oauth_providers", OAuthProviderController
      resources "/search_terms", SearchTermController, only: [:show,:index]
      resources "/tags", UserTagController, only: [:new, :create, :show, :delete, :index], as: :tag
      resources "/job_postings", JobPostingController, param: "job_slug" do
        resources "/tags", JobPostingTagController, as: :tag, only: [:index, :new, :create, :delete]
      end
      resources "/recruiter_subscriptions", RecruiterSubscriptionController, only: [:index, :new, :create]
    end

    post "/users/:slug/tags_create", UserController, :tags_create

    resources "/sessions", SessionController, only: [:new, :create, :delete]
    get "/magic/login/:magiclink", SessionController, :show
    get "/magic/delete/:magiclink", UserController, :magic_delete
    get "/magic/email/:magiclink", EmailController, :magic_create
    get "/follow_back/:id", UserController, :follow_back
  end

  scope "/admin", Vutuv.Admin, as: :admin do
    pipe_through :browser
    resources "/", AdminController, only: [:index]
    post "/slugs", SlugController, :update
    post "/users", UserController, :update
    resources "/locales", LocaleController, only: [:index, :show]
    resources "/exonyms", ExonymController
    resources "/tags", TagController, param: "slug" do
      resources "/tag_localizations", TagLocalizationController, as: :localization do
        resources "/tag_urls", TagUrlController, as: :url
      end
      resources "/tag_synonyms", TagSynonymController, as: :synonym
      resources "/tag_closures", TagClosureController, as: :closure
    end
    resources "/recruiter_packages", RecruiterPackageController, param: "package_slug"
    resources "/coupons", CouponController
  end

  scope "/api/1.0/", as: :api do
    pipe_through :api

    resources "/users", Vutuv.Api.UserController, param: "slug" do

      pipe_through :user_pipe
      get "/vcard", Vutuv.Api.VCardController, :get

      resources "/emails", Vutuv.Api.EmailController, only: [:index, :show]
      pipe_through :render_404
      resources "/slugs", Vutuv.Api.SlugController, only: [:index, :show]

      resources "/groups", Vutuv.Api.GroupController, only: [:index, :show]
      resources "/followers", Vutuv.Api.FollowerController, only: [:index]
      resources "/followees", Vutuv.Api.FolloweeController, only: [:index]

      resources "/phone_numbers", Vutuv.Api.PhoneNumberController, only: [:index, :show]
      resources "/links", Vutuv.Api.UrlController, only: [:index, :show]
      resources "/social_media_accounts", Vutuv.Api.SocialMediaAccountController, only: [:index, :show]
      resources "/work_experiences", Vutuv.Api.WorkExperienceController, only: [:index, :show]
      resources "/addresses", Vutuv.Api.AddressController, only: [:index, :show]
      resources "/search_terms", Vutuv.Api.SearchTermController, only: [:index, :show]

    end

    pipe_through :render_404

  end

  scope "/", as: :default do
    pipe_through :browser
    get "/:slug", Vutuv.PageController, :redirect_user
  end
end

web/models/user.ex
defmodule Vutuv.User do
  use Vutuv.Web, :model
  use Arc.Ecto.Schema
  require Vutuv.Gettext
  @derive {Phoenix.Param, key: :active_slug}

  schema "users" do
    field :first_name, :string
    field :last_name, :string
    field :middlename, :string
    field :nickname, :string
    field :honorific_prefix, :string
    field :honorific_suffix, :string
    field :gender, :string
    field :birthdate, Ecto.Date
    field :locale, :string
    field :verified, :boolean, default: false
    field :avatar, Vutuv.Avatar.Type
    field :active_slug, :string
    field :administrator, :boolean
    field :headline, :string
    field :noindex?, :boolean, default: false
    field :validated?, :boolean, default: false
    field :send_birthday_reminder, :boolean, default: true
    field :easy_tags, :string, virtual: true

    has_many :search_query_requesters,Vutuv.SearchQueryRequester, on_delete: :delete_all
    has_many :search_query_results,   Vutuv.SearchQueryResult,    on_delete: :delete_all
    has_many :oauth_providers,        Vutuv.OAuthProvider,        on_delete: :delete_all
    has_many :magic_links,            Vutuv.MagicLink,            on_delete: :delete_all
    has_many :groups,                 Vutuv.Group,                on_delete: :delete_all
    has_many :emails,                 Vutuv.Email,                on_delete: :delete_all
    has_many :user_tags,              Vutuv.UserTag,              on_delete: :delete_all
    has_many :user_skills,            Vutuv.UserSkill,            on_delete: :delete_all
    has_many :slugs,                  Vutuv.Slug,                 on_delete: :nilify_all, on_replace: :nilify
    has_many :urls,                   Vutuv.Url,                  on_delete: :delete_all
    has_many :phone_numbers,          Vutuv.PhoneNumber,          on_delete: :delete_all
    has_many :addresses,              Vutuv.Address,              on_delete: :delete_all
    has_many :work_experiences,       Vutuv.WorkExperience,       on_delete: :delete_all
    has_many :social_media_accounts,  Vutuv.SocialMediaAccount,   on_delete: :delete_all
    has_many :search_terms,           Vutuv.SearchTerm,           on_delete: :delete_all, on_replace: :delete
    has_many :endorsements,           Vutuv.UserTagEndorsement,   on_delete: :delete_all
    has_many :skill_endorsements,     Vutuv.Endorsement,          on_delete: :delete_all
    has_many :job_postings,           Vutuv.JobPosting,           on_delete: :delete_all
    has_many :recruiter_subscriptions,Vutuv.RecruiterSubscription,on_delete: :delete_all
    has_many :coupons,                Vutuv.Coupon,               on_delete: :delete_all

    has_many :tags, through: [:user_tags, :tag]

    has_many :follower_connections, Vutuv.Connection, foreign_key: :followee_id, on_delete: :delete_all
    has_many :followers, through: [:follower_connections, :follower]

    has_many :followee_connections, Vutuv.Connection, foreign_key: :follower_id, on_delete: :delete_all
    has_many :followees, through: [:followee_connections, :followee]

    timestamps()
  end

  @optional_fields ~w(validated? noindex? headline first_name last_name middlename nickname honorific_prefix honorific_suffix gender birthdate locale active_slug send_birthday_reminder easy_tags)a

  @max_image_filesize Application.fetch_env!(:vutuv, Vutuv.Endpoint)[:max_image_filesize]

  @doc """
  Creates a changeset based on the `model` and `params`.

  If no params are provided, an invalid changeset is returned
  with no validation performed.
  """
  def changeset(model, params \\ %{}) do
    model
    |> cast(params, @optional_fields)
    |> validate_avatar(params)
    |> cast_assoc(:emails)
    |> cast_assoc(:slugs)
    |> cast_assoc(:oauth_providers)
    |> validate_first_name_or_last_name_or_nickname(params)
    |> validate_length(:first_name, max: 50)
    |> validate_length(:last_name, max: 50)
    |> validate_length(:middlename, max: 50)
    |> validate_length(:nickname, max: 50)
    |> validate_length(:honorific_prefix, max: 50)
    |> validate_length(:honorific_suffix, max: 50)
    |> validate_length(:gender, max: 50)
    |> validate_length(:headline, max: 255)
    |> nullify_default_birthdate
    |> downcase_value
  end


  defp validate_avatar(changeset, %{avatar: avatar}), do: validate_avatar(changeset, %{"avatar" => avatar})

  defp validate_avatar(changeset, %{"avatar" => avatar} = params) do
    stat =
      avatar.path
      |>File.stat!
    if(stat.size>@max_image_filesize) do
      add_error(changeset, :avatar, "Avatar filesize is greater than 2MB. Please upload a smaller image.")
    else
      cast_attachments(changeset, params, [:avatar])
    end
  end

  defp validate_avatar(changeset, %{}), do: changeset

  defp validate_first_name_or_last_name_or_nickname(changeset, %{}) do
    first_name = get_field(changeset, :first_name)
    last_name = get_field(changeset, :last_name)
    nickname = get_field(changeset, :nickname)

    if first_name || last_name || nickname do
      # No error if any of those 3 are present.
      #
      changeset
    else
      # All the 3 fields are nil.
      #
      message = "First name or last name or nickname must be present"
      changeset
      |> add_error(:first_name, message)
      |> add_error(:last_name, message)
      |> add_error(:nickname, message)
    end
  end

  def gender_gettext("male") do
    Vutuv.Gettext.gettext("Male")
  end

  def gender_gettext("female") do
    Vutuv.Gettext.gettext("Female")
  end

  def gender_gettext(_) do
    Vutuv.Gettext.gettext("Other")
  end

  defp downcase_value(changeset) do
    # If the value has been changed, downcase it.
    update_change(changeset, :active_slug, &String.downcase/1)
  end

  defp nullify_default_birthdate(changeset) do
    changeset
    |> get_field(:birthdate)
    |> Ecto.Date.dump
    |> check_birthdate(changeset)
  end

  defp check_birthdate({:ok, {1900, 1, 1}}, changeset) do
    changeset
    |> put_change(:birthdate, nil)
  end

  defp check_birthdate(_, changeset), do: changeset

  defimpl String.Chars, for: Vutuv.User do
    def to_string(user), do: "#{user.first_name} #{user.last_name}"
  end

  defimpl List.Chars, for: Vutuv.User do
    def to_charlist(user), do: '#{user.first_name} #{user.last_name}'
  end
end

web/controllers/admin/user_controller.ex
defmodule Vutuv.Admin.UserController do
  use Vutuv.Web, :controller
  plug :logged_in?
  plug Vutuv.Plug.AuthAdmin

  alias Vutuv.User

  def update(conn, %{"user_id"=> user_id}) do
    user = Repo.get(User, user_id)
    changeset = Ecto.Changeset.cast(user, %{verified: true}, [:verified])
    case Repo.update(changeset) do
      {:ok, user} ->
        Vutuv.Emailer.verification_notice(user)
        conn
        |> put_flash(:info, gettext("User verified successfully."))
        |> redirect(to: user_path(conn, :show, user))
      {:error, _changeset} ->
        conn
        |> put_flash(:error, gettext("An error occurred"))
        |> redirect(to: user_path(conn, :show, user))
    end
  end

  defp logged_in?(conn, _opts) do
    if conn.assigns.current_user do
      conn
    else
      conn
      |> put_flash(:error, gettext("You must be logged in to access that page"))
      |> redirect(to: page_path(conn, :index))
      |> halt()
    end
  end
end

web/controllers/api/user_controller.ex
defmodule Vutuv.Api.UserController do
use Vutuv.Web, :controller

  plug Vutuv.Plug.All404
  plug :resolve_slug when action in [:show]
  
  alias Vutuv.User
  alias Vutuv.Slug

  def index(conn, _params) do
    users = Repo.all(User)
    render(conn, "index.json", users: users)
  end

  # def create(conn, %{"user" => user_params}) do
  #   changeset = User.changeset(%User{}, user_params)

  #   case Repo.insert(changeset) do
  #     {:ok, user} ->
  #       conn
  #       |> put_status(:created)
  #       |> put_resp_header("location", user_path(conn, :show, user))
  #       |> render("show.json", user: user)
  #     {:error, changeset} ->
  #       conn
  #       |> put_status(:unprocessable_entity)
  #       |> render(Vutuv.ChangesetView, "error.json", changeset: changeset)
  #   end
  # end

  def show(conn, _params) do
    user = conn.assigns[:user]
    |> Repo.preload([:emails, :work_experiences,
                    :addresses, :phone_numbers,
                    :social_media_accounts, :urls,
                    :followers, :followees,
                    :groups])
    render(conn, "show.json", user: user)
  end

  # def update(conn, %{"id" => id, "user" => user_params}) do
  #   user = Repo.get!(User, id)
  #   changeset = User.changeset(user, user_params)

  #   case Repo.update(changeset) do
  #     {:ok, user} ->
  #       render(conn, "show.json", user: user)
  #     {:error, changeset} ->
  #       conn
  #       |> put_status(:unprocessable_entity)
  #       |> render(Vutuv.ChangesetView, "error.json", changeset: changeset)
  #   end
  # end

  # def delete(conn, %{"id" => id}) do
  #   user = Repo.get!(User, id)

  #   # Here we use delete! (with a bang) because we expect
  #   # it to always work (and if it does not, it will raise).
  #   Repo.delete!(user)

  #   send_resp(conn, :no_content, "")
  # end

  defp resolve_slug(conn, _opts) do
    case conn.params do
      %{"slug" => slug} ->
        case Repo.one(from s in Slug, where: s.value == ^slug) do
          nil  -> invalid_slug(conn)
          %{disabled: false, user_id: user_id} ->
            user = Repo.get!(Vutuv.User, user_id)
            if(user.active_slug != slug) do
              redirect(conn, to: api_user_path(conn, :show, user))
            else
              assign(conn, :user_id, user_id)
            end
          _ -> invalid_slug(conn)
        end
      _ -> invalid_slug(conn)
    end
  end

  defp invalid_slug(conn) do
    conn
    |> put_status(:not_found)
    |> render(Vutuv.ErrorView, "error.json")
    |> halt
  end
end

web/views/admin/user_view.ex
defmodule Vutuv.Admin.UserView do
  use Vutuv.Web, :view
end

web/views/user_view.ex
defmodule Vutuv.UserView do
  use Vutuv.Web, :view
  import Vutuv.UserHelpers

  def avatar_url(user) do
    Vutuv.Avatar.url({user.avatar, user}, :original)
    |> String.replace("web/static/assets", "")
  end
end

web/templates/user/card_list.html.eex
<ul class="button-list profiles">
  <%= for user <- @users do %>
    <li>
      <div class="profile-image">
        <%= link to: user_path(@conn, :show, user) do %>
          <%= if Vutuv.Avatar.sym_link_for_avatar_exists?(user) do %>
            <img src="<%= Vutuv.Avatar.webserver_static_url(user, :thumb) %>" width="50" height="50" alt="Avatar of <%= full_name(user) %>">
          <% else %>
            <img src="<%= Vutuv.Avatar.binary(user, :thumb) %>" width="50" height="50" alt="Avatar of <%= full_name(user) %>">
          <% end %>
        <%= end %>
      </div>
      <p><strong><%= link full_name(user), to: user_path(@conn, :show, user) %></strong>
      <%= work_information_string(user, @work_string_length) %>
      </p>
      <%= if !same_user?(@current_user, user) and @current_user do %>
        <%= if user_follows_user?(@current_user, user) do %>
          <%= button to: connection_path(@conn, :delete, user_follows_user?(@current_user, user)), method: :delete , class: "button button--icon", form: [class: "button button--icon"] do %>
            <i class="icon icon--unfollow"></i>
          <% end %>
        <%= else %>
          <%= button to: connection_path(@conn, :create, connection: %{follower_id: @current_user_id, followee_id: user.id}), method: :post , class: "button button--icon", form: [class: "button button--icon"] do %>
            <i class="icon icon--follow"></i>
          <% end %>
        <% end %>
      <% end %>
    </li>
  <% end %>
</ul>

web/templates/user/edit.html.eex
</header>

<div class="breadcrumbs">
  <%= gen_breadcrumbs([
    gettext("Users"),
    {full_name(@user), user_path(@conn, :show, @user)},
    gettext("Edit")]) %>
</div>

<div class="card-list">
  <section class="card">
    <%= render "form.html", changeset: @changeset, action: user_path(@conn, :update, @user), conn: @conn, current_user: @current_user, backlink: user_path(@conn, :show, @user) %>
	</section>
  <aside>
    <%= render Vutuv.SharedView, "_ad.html", assigns %>
    <section class="card">
      <h1><%= gettext "Administration" %></h1>
      <%= button gettext("Delete Account"), to: user_path(@conn, :delete, @user), method: "delete", class: "link_button delete_link_button", form: [class: "link_button_form card__morelink-border"] %>
    </section>
  </aside>
</div>

web/templates/user/form.html.eex
  <%= form_for @changeset, @action, [multipart: true, class: "editform"], fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p class="editform__error"><%= gettext "Oops, something went wrong! Please check the errors below." %></p>
    </div>
  <% end %>
  <%= if @current_user do %>
    <div class="editform__field<%= if error_tag(f, :avatar), do: " editform__field--error"%>">
    <%= label f, :avatar, gettext("Avater") %>
    <div class="editform__inputwrap<%= if error_tag(f, :avatar), do: " editform__field--error"%>">
      <%= file_input f, :avatar %>
    </div>
    <%= error_tag f, :avatar %>
    </div>
  <% end %>

  <div class="editform__field<%= if error_tag(f, :gender), do: " editform__field--error"%>">
  <%= label f, :gender, gettext("Gender") %>
  <%= select f, :gender, [{gettext("male"), "male"}, {gettext("female"), "female"}, {gettext("other"), "other"}], id: "gender", prompt: gettext("Choose a gender") %>
  <%= error_tag f, :gender %>
  </div>

  <div class="editform__field<%= if error_tag(f, :first_name), do: " editform__field--error"%>">
  <%= label f, :first_name, gettext("First Name") %>
  <%= text_input f, :first_name, autofocus: true %>
  <%= error_tag f, :first_name %>
  </div>

  <div class="editform__field<%= if error_tag(f, :last_name), do: " editform__field--error"%>">
  <%= label f, :last_name, gettext("Last Name") %>
  <%= text_input f, :last_name %>
  <%= error_tag f, :last_name %>
  </div>


  <%= inputs_for f, :emails, fn ef -> %>
  <%= label ef, :email_address, gettext("Email Address") %>
  <div class="editform__field<%= if error_tag(ef, :value), do: " editform__field--error"%>">
    <%= email_input ef, :value %>
    <%= error_tag ef, :value %>
  </div>
  <div class="editform__field<%= if error_tag(f, :public?), do: " editform__field--error"%>">
    <%= label ef, :public?, gettext("Is this email public or private?") %>
    <%= select ef, :public?, ["Public": true, "Private": false] %>
    <%= error_tag ef, :public? %>
  </div>
  <% end %>

  <%= if @current_user do %>
    <div class="editform__field<%= if error_tag(f, :middlename), do: " editform__field--error"%>">
    <%= label f, :middlename, gettext("Middle Name") %>
    <%= text_input f, :middlename %>
    <%= error_tag f, :middlename %>
    </div>

    <div class="editform__field<%= if error_tag(f, :nickname), do: " editform__field--error"%>">
    <%= label f, :nickname, gettext("Nickname") %>
    <%= text_input f, :nickname %>
    <%= error_tag f, :nickname %>
    </div>

    <div class="editform__field<%= if error_tag(f, :honorific_prefix), do: " editform__field--error"%>">
    <%= label f, :honorific_prefix, gettext("Prefix") %>
    <%= text_input f, :honorific_prefix %>
    <%= error_tag f, :honorific_prefix %>
    </div>

    <div class="editform__field<%= if error_tag(f, :honorific_suffix), do: " editform__field--error"%>">
    <%= label f, :honorific_suffix, gettext("Suffix") %>
    <%= text_input f, :honorific_suffix %>
    <%= error_tag f, :honorific_suffix %>
    </div>

    <div class="editform__field<%= if error_tag(f, :birthdate), do: " editform__field--error"%>">
    <%= label f, :birthdate, gettext("Birthdate") %>
    <div class="editform__inputwrap">
      <%= date_select f, :birthdate, year: [options: 1900..2100] %>
    </div>
    <%= error_tag f, :birthdate %>
    </div>

    <div class="editform__field<%= if error_tag(f, :headline), do: " editform__field--error"%>">
    <%= label f, :headline, gettext("Headline") %>
    <%= textarea f, :headline %>
    <%= error_tag f, :headline %>
    </div>

    <div class="editform__field<%= if error_tag(f, :locale), do: " editform__field--error"%>">
    <%= label f, :locale, gettext("Language") %>
    <%= select f, :locale, [{gettext("English"), "en"}, {gettext("German"), "de"}] %>
    <%= error_tag f, :locale %>
    </div>
  <% end %>

  <div class="editform__field<%= if error_tag(f, :noindex?), do: " editform__field--error"%>">
    <%= label f, :noindex?, gettext("Would you like to allow search engines to index your profile?") %>
    <%= select f, :noindex?, [{gettext("Yes"), false}, {gettext("No"), true}] %>
    <%= error_tag f, :noindex? %>
  </div>

  <div class="editform__field<%= if error_tag(f, :noindex?), do: " editform__field--error"%>">
    <%= label f, :send_birthday_reminder, gettext("Would you like to receive birthday reminder emails?") %>
    <%= select f, :send_birthday_reminder, [{gettext("Yes"), true}, {gettext("No"), false}] %>
    <%= error_tag f, :send_birthday_reminder %>
  </div>

  <div class="editform__actions">
    <%= link gettext("Cancel"), to: @backlink, class: "button button--cancel" %>
    <%= submit if((@current_user), do: gettext("Save"), else: gettext("Create Account")), class: "button" %>
  </div>
<% end %>

web/templates/user/index.html.eex
<h2>Users</h2>

<table class="pure-table pure-table-horizontal">
  <thead>
    <tr>
      <th><%= gettext "First name" %></th>
      <th><%= gettext "Last name" %></th>
      <th><%= gettext "Middlename" %></th>
      <th><%= gettext "Nickname" %></th>
      <th><%= gettext "Honorific prefix" %></th>
      <th><%= gettext "Honorific suffix" %></th>
      <th><%= gettext "Gender" %></th>
      <th><%= gettext "Birthdate" %></th>
      <th><%= gettext "Verified" %></th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for user <- @users do %>
    <tr>
      <td><%= user.first_name %></td>
      <td><%= user.last_name %></td>
      <td><%= user.middlename %></td>
      <td><%= user.nickname %></td>
      <td><%= user.honorific_prefix %></td>
      <td><%= user.honorific_suffix %></td>
      <td><%= user.gender %></td>
      <td><%= user.birthdate %></td>
      <td><%= user.verified %></td>

      <td class="text-right">
        <%= link gettext("Show"), to: user_path(@conn, :show, user), class: "btn btn-default btn-xs" %>
        <%= link gettext("Edit"), to: user_path(@conn, :edit, user), class: "btn btn-default btn-xs" %>
        <%= link gettext("Delete"), to: user_path(@conn, :delete, user), method: :delete, data: [confirm: gettext("Are you sure?")], class: "btn btn-danger btn-xs" %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<%= link "New user", to: user_path(@conn, :new) %>

web/templates/user/new.html.eex
</header>

<div class="breadcrumbs">
  <%= gen_breadcrumbs([
    gettext("Users"),
    gettext("New")]) %>
</div>

<div class="card-list">

  <aside>
    <%= render Vutuv.SharedView, "_ad.html", assigns %>
  </aside>
  <section class="card">
    <%= render "form.html", backlink: page_path(@conn, :index), changeset: @changeset, current_user: @current_user, action: user_path(@conn, :create) %>
  </section>
</div>