web/router.ex
defmodule Vutuv.Router do
  use Vutuv.Web, :router
  alias Vutuv.Plug, as: Plug

  if Mix.env == :dev do
    forward "/sent_emails", Bamboo.EmailPreviewPlug
  end

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    #plug Vutuv.Plug.ManageCookies
    plug :put_secure_browser_headers
    plug Plug.ConfigureSession, repo: Vutuv.Repo
    plug Plug.Locale
  end

  pipeline :user_pipe do
    plug Plug.UserResolveSlug
    plug Plug.EnsureValidated
  end

  pipeline :api do
    plug :accepts, ["json-api"]
    plug Plug.PutAPIHeaders
    plug Plug.Locale
  end

  pipeline :render_404 do
    plug Plug.All404
  end

  scope "/", Vutuv do
    pipe_through :browser # Use the default browser stack


    resources "/tags", TagController, only: [:index, :show], param: "slug"

    get "/", PageController, :index
    get "/impressum", PageController, :impressum
    get "/listings/most_followed_users", PageController, :most_followed_users
    get "/new_registration", PageController, :redirect_index
    post "/new_registration", PageController, :new_registration

    # TODO: delete the following route entries
    resources "/memberships", MembershipController, only: [:create, :delete]
    resources "/connections", ConnectionController, only: [:create, :delete] do
      resources "/memberships", MembershipController, only: [:create, :delete]
    end

    resources "/search_queries", SearchQueryController, only: [:create, :new, :show]

    resources "/users", UserController, param: "slug" do
      pipe_through :user_pipe
      resources "/emails", EmailController
      resources "/slugs", SlugController, only: [:index, :new, :create, :show, :update]
      resources "/groups", GroupController
      resources "/followers", FollowerController, only: [:index]
      resources "/followees", FolloweeController, only: [:index]
      resources "/user_tag_endorsements", UserTagEndorsementController, only: [:create, :delete], as: :tag_endorsement
      resources "/phone_numbers", PhoneNumberController
      resources "/dates", DateController
      resources "/links", UrlController
      resources "/social_media_accounts", SocialMediaAccountController
      resources "/work_experiences", WorkExperienceController
      resources "/addresses", AddressController
      resources "/oauth_providers", OAuthProviderController
      resources "/search_terms", SearchTermController, only: [:show,:index]
      resources "/tags", UserTagController, only: [:new, :create, :show, :delete, :index], as: :tag
      resources "/job_postings", JobPostingController, param: "job_slug" do
        resources "/tags", JobPostingTagController, as: :tag, only: [:index, :new, :create, :delete]
      end
      resources "/recruiter_subscriptions", RecruiterSubscriptionController, only: [:index, :new, :create]
    end

    post "/users/:slug/tags_create", UserController, :tags_create

    resources "/sessions", SessionController, only: [:new, :create, :delete]
    get "/magic/login/:magiclink", SessionController, :show
    get "/magic/delete/:magiclink", UserController, :magic_delete
    get "/magic/email/:magiclink", EmailController, :magic_create
    get "/follow_back/:id", UserController, :follow_back
  end

  scope "/admin", Vutuv.Admin, as: :admin do
    pipe_through :browser
    resources "/", AdminController, only: [:index]
    post "/slugs", SlugController, :update
    post "/users", UserController, :update
    resources "/locales", LocaleController, only: [:index, :show]
    resources "/exonyms", ExonymController
    resources "/tags", TagController, param: "slug" do
      resources "/tag_localizations", TagLocalizationController, as: :localization do
        resources "/tag_urls", TagUrlController, as: :url
      end
      resources "/tag_synonyms", TagSynonymController, as: :synonym
      resources "/tag_closures", TagClosureController, as: :closure
    end
    resources "/recruiter_packages", RecruiterPackageController, param: "package_slug"
    resources "/coupons", CouponController
  end

  scope "/api/1.0/", as: :api do
    pipe_through :api

    resources "/users", Vutuv.Api.UserController, param: "slug" do

      pipe_through :user_pipe
      get "/vcard", Vutuv.Api.VCardController, :get

      resources "/emails", Vutuv.Api.EmailController, only: [:index, :show]
      pipe_through :render_404
      resources "/slugs", Vutuv.Api.SlugController, only: [:index, :show]

      resources "/groups", Vutuv.Api.GroupController, only: [:index, :show]
      resources "/followers", Vutuv.Api.FollowerController, only: [:index]
      resources "/followees", Vutuv.Api.FolloweeController, only: [:index]

      resources "/phone_numbers", Vutuv.Api.PhoneNumberController, only: [:index, :show]
      resources "/links", Vutuv.Api.UrlController, only: [:index, :show]
      resources "/social_media_accounts", Vutuv.Api.SocialMediaAccountController, only: [:index, :show]
      resources "/work_experiences", Vutuv.Api.WorkExperienceController, only: [:index, :show]
      resources "/addresses", Vutuv.Api.AddressController, only: [:index, :show]
      resources "/search_terms", Vutuv.Api.SearchTermController, only: [:index, :show]

    end

    pipe_through :render_404

  end

  scope "/", as: :default do
    pipe_through :browser
    get "/:slug", Vutuv.PageController, :redirect_user
  end
end

web/views/layout_view.ex
defmodule Vutuv.LayoutView do
  use Vutuv.Web, :view
  import Vutuv.UserHelpers

  defp embed_css(conn) do
    filepath = 
    Application.app_dir(:vutuv, "/priv/static")<>static_path(conn, "/css/app.css")
    |> String.replace("?vsn=d", "")
    case File.read(filepath) do
      {:ok, data} -> "<style>\n#{data}\n</style>"
      {:error, _} -> "<link rel=\"stylesheet\" href=\"#{static_path(conn, "/css/app.css")}\">"
    end
    |> raw
  end
end

web/templates/layout/app.html.eex
<!doctype html>
<html lang="<%= @locale %>">
    <head>
    <%= if @conn.assigns[:user] do %>
      <%= if @user.noindex? do %>
        <meta name="robots" content="noindex">
      <% end %>
    <% end %>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title><%= if @conn.assigns[:user], do: "#{full_name(@conn.assigns[:user])} - vutuv", else: "vutuv" %></title>
        <%= if @conn.assigns[:user] do %>
        <meta name="description" content="<%= meta_description(@user, @conn.assigns[:user_tags]) %>">
        <% else %>
        <meta name="description" content="<%= gettext("Your Fast and Free Career Network. No expensive premium accounts! Get a free account in 30 seconds.") %>">
        <%= if @conn.assigns[:prefetch] do %>
          <link rel="prefetch" title="Most followed users" href="/listings/most_followed_users">
        <% end %>
        <% end %>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="shortcut icon" href="/favicon.ico">
        <link rel="icon" href="/favicon.ico">
        <meta name="theme-color" content="#ffffff">
        <%= embed_css @conn %>
    </head>
    <body class = "<%= @conn.assigns[:body_class] %>">

<header>
  <nav class="navigation">
    <div>
    <%= if @conn.assigns[:current_user] do %>
      <%= button to: session_path(@conn, :delete, @current_user), method: "delete", class: "button button--icon navigation__icon", form: [style: "flex: 1;", class: "button button--icon"] do %>
      <i title="<%= gettext("Log Out") %>" class="icon icon--lock"></i>
      <% end %>
    <% else %>
      <%= link to: session_path(@conn, :new), class: "navigation__icon" do %>
      <i title="<%= gettext("Log In") %>" class="icon icon--lock"></i>
      <% end %>
    <% end %>

      <a href="/"><img src="data:image/svg+xml,%3Csvg%20xmlns%3D%27http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%27%20viewBox%3D%270%200%20134.35%2034.65%27%3E%3Ctitle%3Elogo%3C%2Ftitle%3E%3Cpath%20d%3D%27M10.19%2034.05q-2.56-5-5.19-11.7T0%207.75h7.9q.5%202%201.18%204.23t1.41%204.6q.73%202.32%201.46%204.52t1.43%204q.65-1.8%201.4-4t1.48-4.52q.73-2.33%201.41-4.6t1.18-4.23h7.7q-2.36%207.9-5%2014.6t-5.19%2011.7zM52.95%2033.15a41.42%2041.42%200%200%201-4.9%201%2040.27%2040.27%200%200%201-6.3.47%2014.94%2014.94%200%200%201-5.58-.9%208.46%208.46%200%200%201-3.53-2.5%209.85%209.85%200%200%201-1.85-3.88%2020.82%2020.82%200%200%201-.55-5V7.75h7.45V21.5a10.65%2010.65%200%200%200%201%205.2q.95%201.6%203.55%201.6.8%200%201.7-.08t1.6-.17V7.75h7.45zM59.7%201.2L67.15%200v7.75h9v6.2h-9v9.25a7.36%207.36%200%200%200%20.83%203.75q.82%201.4%203.32%201.4a14.2%2014.2%200%200%200%202.48-.23%2012.62%2012.62%200%200%200%202.33-.62l1%205.8a21.08%2021.08%200%200%201-3%20.95%2017.51%2017.51%200%200%201-4.05.4%2013.34%2013.34%200%200%201-5-.82%207.91%207.91%200%200%201-3.2-2.3%208.54%208.54%200%200%201-1.67-3.58%2021%2021%200%200%201-.48-4.65zM117.99%2034.05q-2.56-5-5.19-11.7t-5-14.6h7.9q.5%202%201.18%204.23t1.41%204.6q.73%202.32%201.46%204.52t1.43%204q.65-1.8%201.4-4t1.48-4.52q.73-2.33%201.41-4.6t1.17-4.23h7.7q-2.36%207.9-5%2014.6t-5.19%2011.7zM81.9%2033.15a41.38%2041.38%200%200%200%204.9%201%2040.26%2040.26%200%200%200%206.3.47%2014.94%2014.94%200%200%200%205.58-.9%208.46%208.46%200%200%200%203.53-2.52%209.84%209.84%200%200%200%201.85-3.88%2020.8%2020.8%200%200%200%20.55-5V7.75h-7.46V21.5a10.65%2010.65%200%200%201-1%205.2q-.95%201.6-3.55%201.6-.8%200-1.7-.08t-1.6-.17V7.75h-7.4z%27%20fill%3D%27%231a1918%27%2F%3E%3C%2Fsvg%3E"></a>
      <%= link to: search_query_path(@conn, :new), class: "navigation__icon  navigation__icon--right" do %>
      <i title="<%= gettext "Search" %>" class="icon icon--search"></i>
      <% end %>
    </div>
  </nav>

  <%= render @view_module, @view_template, assigns %>

  <footer>
    <p>
      Copyright © 2017 <a href="https://www.wintermeyer-consulting.de">Wintermeyer Consulting</a> | <a href="https://github.com/vutuv/vutuv/"> Source-Code</a> |
      <a href="https://github.com/vutuv/vutuv/issues/new"><%= gettext "Submit a bugreport or a feature request." %></a> | <a href="/privacy-policy.html"><%= gettext "Privacy Policy" %></a> | <%= link gettext("About us"), to: page_path(@conn, :impressum) %></a> | vutuv <%= Application.spec(:vutuv, :vsn) %>
    </p>
  </footer>
</body>
</html>

web/templates/layout/flash.html.eex
<%= if get_flash(@conn, :info) do %>
  <div class="message message--success"><p><%= get_flash(@conn, :info) %></p></div>
<% end %>
<%= if get_flash(@conn, :error) do %>
  <div class="message message--error"><p><%= get_flash(@conn, :error) %></p></div>
<% end %>

web/templates/layout/no_layout.html.eex
<%= render @view_module, @view_template, assigns %>