web/router.ex
defmodule Vutuv.Router do
  use Vutuv.Web, :router
  alias Vutuv.Plug, as: Plug

  if Mix.env == :dev do
    forward "/sent_emails", Bamboo.EmailPreviewPlug
  end

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    #plug Vutuv.Plug.ManageCookies
    plug :put_secure_browser_headers
    plug Plug.ConfigureSession, repo: Vutuv.Repo
    plug Plug.Locale
  end

  pipeline :user_pipe do
    plug Plug.UserResolveSlug
    plug Plug.EnsureValidated
  end

  pipeline :api do
    plug :accepts, ["json-api"]
    plug Plug.PutAPIHeaders
    plug Plug.Locale
  end

  pipeline :render_404 do
    plug Plug.All404
  end

  scope "/", Vutuv do
    pipe_through :browser # Use the default browser stack


    resources "/tags", TagController, only: [:index, :show], param: "slug"

    get "/", PageController, :index
    get "/impressum", PageController, :impressum
    get "/listings/most_followed_users", PageController, :most_followed_users
    get "/new_registration", PageController, :redirect_index
    post "/new_registration", PageController, :new_registration

    # TODO: delete the following route entries
    resources "/memberships", MembershipController, only: [:create, :delete]
    resources "/connections", ConnectionController, only: [:create, :delete] do
      resources "/memberships", MembershipController, only: [:create, :delete]
    end

    resources "/search_queries", SearchQueryController, only: [:create, :new, :show]

    resources "/users", UserController, param: "slug" do
      pipe_through :user_pipe
      resources "/emails", EmailController
      resources "/slugs", SlugController, only: [:index, :new, :create, :show, :update]
      resources "/groups", GroupController
      resources "/followers", FollowerController, only: [:index]
      resources "/followees", FolloweeController, only: [:index]
      resources "/user_tag_endorsements", UserTagEndorsementController, only: [:create, :delete], as: :tag_endorsement
      resources "/phone_numbers", PhoneNumberController
      resources "/dates", DateController
      resources "/links", UrlController
      resources "/social_media_accounts", SocialMediaAccountController
      resources "/work_experiences", WorkExperienceController
      resources "/addresses", AddressController
      resources "/oauth_providers", OAuthProviderController
      resources "/search_terms", SearchTermController, only: [:show,:index]
      resources "/tags", UserTagController, only: [:new, :create, :show, :delete, :index], as: :tag
      resources "/job_postings", JobPostingController, param: "job_slug" do
        resources "/tags", JobPostingTagController, as: :tag, only: [:index, :new, :create, :delete]
      end
      resources "/recruiter_subscriptions", RecruiterSubscriptionController, only: [:index, :new, :create]
    end

    post "/users/:slug/tags_create", UserController, :tags_create

    resources "/sessions", SessionController, only: [:new, :create, :delete]
    get "/magic/login/:magiclink", SessionController, :show
    get "/magic/delete/:magiclink", UserController, :magic_delete
    get "/magic/email/:magiclink", EmailController, :magic_create
    get "/follow_back/:id", UserController, :follow_back
  end

  scope "/admin", Vutuv.Admin, as: :admin do
    pipe_through :browser
    resources "/", AdminController, only: [:index]
    post "/slugs", SlugController, :update
    post "/users", UserController, :update
    resources "/locales", LocaleController, only: [:index, :show]
    resources "/exonyms", ExonymController
    resources "/tags", TagController, param: "slug" do
      resources "/tag_localizations", TagLocalizationController, as: :localization do
        resources "/tag_urls", TagUrlController, as: :url
      end
      resources "/tag_synonyms", TagSynonymController, as: :synonym
      resources "/tag_closures", TagClosureController, as: :closure
    end
    resources "/recruiter_packages", RecruiterPackageController, param: "package_slug"
    resources "/coupons", CouponController
  end

  scope "/api/1.0/", as: :api do
    pipe_through :api

    resources "/users", Vutuv.Api.UserController, param: "slug" do

      pipe_through :user_pipe
      get "/vcard", Vutuv.Api.VCardController, :get

      resources "/emails", Vutuv.Api.EmailController, only: [:index, :show]
      pipe_through :render_404
      resources "/slugs", Vutuv.Api.SlugController, only: [:index, :show]

      resources "/groups", Vutuv.Api.GroupController, only: [:index, :show]
      resources "/followers", Vutuv.Api.FollowerController, only: [:index]
      resources "/followees", Vutuv.Api.FolloweeController, only: [:index]

      resources "/phone_numbers", Vutuv.Api.PhoneNumberController, only: [:index, :show]
      resources "/links", Vutuv.Api.UrlController, only: [:index, :show]
      resources "/social_media_accounts", Vutuv.Api.SocialMediaAccountController, only: [:index, :show]
      resources "/work_experiences", Vutuv.Api.WorkExperienceController, only: [:index, :show]
      resources "/addresses", Vutuv.Api.AddressController, only: [:index, :show]
      resources "/search_terms", Vutuv.Api.SearchTermController, only: [:index, :show]

    end

    pipe_through :render_404

  end

  scope "/", as: :default do
    pipe_through :browser
    get "/:slug", Vutuv.PageController, :redirect_user
  end
end

web/models/tag.ex
defmodule Vutuv.Tag do
  use Vutuv.Web, :model
  @derive {Phoenix.Param, key: :slug}


  schema "tags" do
    field :slug, :string

    has_many :tag_localizations, Vutuv.TagLocalization, on_delete: :delete_all
    has_many :tag_synonyms, Vutuv.TagSynonym, on_delete: :delete_all

    has_many :parent_closures, Vutuv.TagClosure, foreign_key: :child_id, on_delete: :delete_all
    has_many :parents, through: [:parent_closures, :parent]

    has_many :child_closures, Vutuv.TagClosure, foreign_key: :parent_id, on_delete: :delete_all
    has_many :children, through: [:child_closures, :child]

    has_many :user_tags, Vutuv.UserTag, on_delete: :delete_all
    has_many :job_posting_tags, Vutuv.JobPostingTag, on_delete: :delete_all

    timestamps()
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}, locale \\ "en")

  def changeset(struct, %{"value" => value} = params, locale) do
    struct
    |> cast(params, [:slug])
    |> gen_slug(value)
    |> validate_required([:slug])
    |> validate_length(:slug, max: 60)
    |> unique_constraint(:slug)
    |> default_localization(value, locale)
  end

  def changeset(struct, params, locale) do
    struct
    |> cast(params, [:slug])
    |> validate_required([:slug])
    |> validate_length(:slug, max: 60)
    |> unique_constraint(:slug)
    |> default_localization(params["slug"], locale)
  end

  def edit_changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:slug])
    |> validate_required([:slug])
    |> unique_constraint(:slug)
    |> validate_length(:slug, max: 60)
  end

  def gen_slug(changeset, value) do
    slug =
      value
      |> Vutuv.SlugHelpers.gen_slug_unique( __MODULE__, :slug, ?_)
    put_change(changeset, :slug, slug)
  end

  def default_localization(changeset, value, locale) do
    localization =
      %Vutuv.TagLocalization{}
      |> Vutuv.TagLocalization.changeset(%{name: value, locale_id: Vutuv.Locale.locale_id(locale)})
    changeset
    |> put_assoc(:tag_localizations, [localization])
  end

  def create_or_link_tag(changeset, %{"value" => value} = params, locale) do
    downcase_value = String.downcase(value)
    Vutuv.Repo.one(from t in __MODULE__,
      left_join: syn in assoc(t, :tag_synonyms),
      left_join: loc in assoc(t, :tag_localizations),
      where: syn.value == ^downcase_value or loc.name == ^downcase_value, limit: 1)
    |> case do
      nil ->
        tag = __MODULE__.changeset(%__MODULE__{}, params, locale)
        put_assoc(changeset, :tag, tag)
      tag ->
        put_change(changeset, :tag_id, tag.id)
    end
  end

  def resolve_localization(tag, locale) do
    Vutuv.Repo.one(from(t in Vutuv.TagLocalization,
      where: t.locale_id == ^(Vutuv.Locale.locale_id(locale)) and
      t.tag_id == ^tag.id,
      preload: [:tag_urls]))
    ||
    Vutuv.Repo.one(from(t in Vutuv.TagLocalization,
      where: t.tag_id == ^tag.id,
      preload: [:tag_urls],
      limit: 1))
  end

  def related_users(_, nil), do: []

  def related_users(tag, current_user) do
    (Vutuv.Repo.all(from u in assoc(current_user, :followers),
      left_join: us in assoc(u, :user_tags),
      left_join: e in assoc(us, :endorsements),
      where: us.tag_id == ^tag.id,
      order_by: fragment("count(?) DESC", e.id), #most endorsed
      group_by: u.id,
      limit: 10)
    ++
    Vutuv.Repo.all(from u in assoc(current_user, :followees),
      left_join: us in assoc(u, :user_tags),
      left_join: e in assoc(us, :endorsements),
      where: us.tag_id == ^tag.id,
      order_by: fragment("count(?) DESC", e.id), #most endorsed
      group_by: u.id,
      limit: 10))
    |> Enum.uniq_by(&(&1.id))
  end

  def reccomended_users(tag) do
    Vutuv.Repo.all(from u in Vutuv.User,
      left_join: us in assoc(u, :user_tags),
      left_join: e in assoc(us, :endorsements),
      where: us.tag_id == ^tag.id,
      order_by: fragment("count(?) DESC", e.id), #most endorsed
      group_by: u.id,
      limit: 10)
  end

  def resolve_name(tag, locale) do
    tag = Vutuv.Repo.preload(tag, [tag_localizations: :locale])
    localization =
      Enum.reduce(tag.tag_localizations, fn f, acc ->
        if(f.locale.value == locale) do
          f
        else
          acc
        end
      end)
    localization.name
  end

  defimpl String.Chars, for: Vutuv.Tag do
    def to_string(tag), do: "#{tag.slug}"
  end

  defimpl List.Chars, for: Vutuv.Tag do
    def to_charlist(tag), do: '#{tag.slug}'
  end
end

web/controllers/admin/tag_controller.ex
defmodule Vutuv.Admin.TagController do
  use Vutuv.Web, :controller
  plug :logged_in?
  plug Vutuv.Plug.AuthAdmin
  plug :resolve_tag

  alias Vutuv.Tag

  def index(conn, _params) do
    tags = Repo.all(Tag)
    render(conn, "index.html", tags: tags)
  end

  def new(conn, _params) do
    changeset = Tag.changeset(%Tag{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"tag" => tag_params}) do
    changeset = Tag.changeset(%Tag{}, tag_params, conn.assigns[:locale])

    case Repo.insert(changeset) do
      {:ok, _tag} ->
        conn
        |> put_flash(:info, gettext("Tag created successfully."))
        |> redirect(to: admin_tag_path(conn, :index))
      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, _params) do
    tag =
      conn.assigns[:tag]
      |> Repo.preload([
        tag_synonyms: from(f in Vutuv.TagSynonym,  limit: 5, preload: [:tag, :locale]),
        tag_localizations: from(f in Vutuv.TagLocalization, limit: 5, preload: [:tag, :locale, :tag_urls])])
    render(conn, "show.html", tag: tag)
  end

  def edit(conn, _params) do
    tag =  conn.assigns[:tag]
    changeset = Tag.edit_changeset(tag)
    render(conn, "edit.html", tag: tag, changeset: changeset)
  end

  def update(conn, %{"tag" => tag_params}) do
    tag = 
      conn.assigns[:tag]
    changeset = Tag.edit_changeset(tag, tag_params)

    case Repo.update(changeset) do
      {:ok, tag} ->
        conn
        |> put_flash(:info, gettext("Tag updated successfully."))
        |> redirect(to: admin_tag_path(conn, :show, tag))
      {:error, changeset} ->
        render(conn, "edit.html", tag: tag, changeset: changeset)
    end
  end

  def delete(conn, _params) do

    # Here we use delete! (with a bang) because we expect
    # it to always work (and if it does not, it will raise).
    Repo.delete!(conn.assigns[:tag])

    conn
    |> put_flash(:info, gettext("Tag deleted successfully."))
    |> redirect(to: admin_tag_path(conn, :index))
  end

  defp resolve_tag(%{params: %{"slug" => slug}} = conn, _opts) do
    Repo.one(from t in Vutuv.Tag, where: t.slug == ^slug)
    |> case do
      nil -> 
        conn
        |> put_status(:not_found)
        |> render(Vutuv.ErrorView, "404.html")
        |> halt
      tag ->
        assign(conn, :tag, tag)
    end
  end

  defp resolve_tag(conn, _opts), do: conn

  defp logged_in?(conn, _opts) do
    if conn.assigns.current_user do
      conn
    else
      conn
      |> put_flash(:error, gettext("You must be logged in to access that page"))
      |> redirect(to: page_path(conn, :index))
      |> halt()
    end
  end
end

web/controllers/tag_controller.ex
defmodule Vutuv.TagController do
  use Vutuv.Web, :controller

  alias Vutuv.Tag

  plug :resolve_tag

  def index(conn, _params) do
    tags_count = Repo.one(from t in Tag, select: count(t.id))
    tags =
      from(t in Tag)
      |> Vutuv.Pages.paginate(conn.params, tags_count)
      |> Repo.all
    render(conn, "index.html", tags: tags, tags_count: tags_count)
  end

  def show(conn, _params) do
    tag = conn.assigns[:tag]
    render(conn, "show.html", tag: tag, loc: Vutuv.Tag.resolve_localization(tag, conn.assigns[:locale]))
  end

  defp resolve_tag(%{params: %{"slug" => slug}} = conn, _opts) do
    Repo.one(from t in Vutuv.Tag, where: t.slug == ^slug)
    |> case do
      nil ->
        conn
        |> put_status(:not_found)
        |> render(Vutuv.ErrorView, "404.html")
        |> halt
      tag ->
        assign(conn, :tag, tag)
    end
  end

  defp resolve_tag(conn, _opts), do: conn
end

web/views/admin/tag_view.ex
defmodule Vutuv.Admin.TagView do
  use Vutuv.Web, :view
end

web/views/tag_view.ex
defmodule Vutuv.TagView do
  use Vutuv.Web, :view
  import Vutuv.UserHelpers

  defp update_assigns(assigns) do
  	assigns
  	|> Map.put(:related_users, Vutuv.Tag.related_users(assigns[:tag], assigns[:current_user]))
  	|> Map.put(:reccomended_users, Vutuv.Tag.reccomended_users(assigns[:tag]))
  	|> Map.put(:work_string_length, 45)
  end
end

web/templates/tag/card_list.html.eex
<table>
  <thead>
    <tr>
      <th><%= gettext "Tag name" %></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <%= for tag <- @tags do %>
    <tr>
      <td>
      <p style="word-wrap: break-word; max-width: 600px;"><%= link Vutuv.Tag.resolve_name(tag, @conn.assigns.locale), to: tag_path(@conn, :show, tag) %></p>
      </td>
      <td>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

web/templates/tag/index.html.eex
  <div class="profile-header">
    <div class="profile-header__info">
      <h1><%= gettext "All tags" %></h1>
    </div>
  </div>
</header>
<%= render Vutuv.LayoutView, "flash.html", assigns %>

<div class="breadcrumbs">
  <%= Vutuv.UserHelpers.gen_breadcrumbs([
      gettext("Tags")]) %>
</div>

<div class="card-list">
  <section class="card">
  <h1> <%= gettext("Tags") %> </h1>
    <table>
      <thead>
        <tr>
          <th><%= gettext "Slug" %></th>

          <th></th>
        </tr>
      </thead>
      <tbody>
    <%= for {tag, _index} <- Enum.with_index(@tags) do %>
        <tr>
          <td><%= tag.slug %></td>

          <td>
            <%= link to: tag_path(@conn, :show, tag), class: "button button--icon button--small" do %>
            <i class="icon icon--search"></i>
            <% end %>
          </td>
        </tr>
    <% end %>
      </tbody>
    </table>
    <%= Vutuv.Pages.page_list(@conn.params, @tags_count) %>
  </section>
  <aside>
    <%= render Vutuv.SharedView, "_ad.html", assigns %>
  </aside>
</div>

web/templates/tag/show.html.eex
  <div class="profile-header">
    <div class="profile-header__info">
      <h1><%= @loc.name %></h1>
    </div>
  </div>
</header>
<%= render Vutuv.LayoutView, "flash.html", assigns %>

<div class="breadcrumbs">
<%= Vutuv.UserHelpers.gen_breadcrumbs([
      {gettext("Tags"), tag_path(@conn, :index)},
      gettext("Show")]) %>
</div>

<div class="card-list">
    <%= render "single_card.html", assigns %>
</div>

web/templates/tag/single_card.html.eex
<% loc = Vutuv.Tag.resolve_localization(@tag, @conn.assigns[:locale]) %>
<section class="card">
	
	<% assigns = update_assigns(assigns) %>
	<%= if(loc.description) do %>
	<h1><%= gettext("Description") %></h1>
  <p><%= loc.description %></p>
  <% else %>
  <p><%= gettext("This skill doesn't have a description yet.") %></p>
	<% end %>
	<%= if Enum.count(@related_users) > 0 do %>
		<h1><%= gettext("People you may know with this tag") %></h1>
		<%= render Vutuv.UserView, "card_list.html", Map.put(assigns, :users, @related_users) %>
	<% end %>
	<%= if Enum.count(@reccomended_users) > 0 do %>
		<h1><%= gettext("The most endorsed users with this tag") %></h1>
		<%= render Vutuv.UserView, "card_list.html", Map.put(assigns, :users, @reccomended_users) %>
	<% end %>
  <%= if @conn.assigns[:current_user] && !(has_tag?(assigns[:current_user], assigns[:tag])) do %>
  <%= button to: user_tag_path(@conn, :create, @current_user, tag_param: [value: Vutuv.Tag.resolve_name(@tag, @conn.assigns[:locale])]), method: :post, class: "link_button", form: [class: "link_button_form card__morelink-border"] do %>
  <i class="icon icon--plus"></i> Add This tag
  <% end %>
  <% end %>
</section>
<aside>
  <%= render Vutuv.SharedView, "_ad.html", assigns %>
  <section class="card">
    <h1> <%= if (Enum.count(loc.tag_urls) == 1), do: gettext("Url"), else: gettext("Urls") %> </h1>
    <dl class="email-list">
      <%= for url <- loc.tag_urls do %>
      <dt class="email-list"><span style="font-weight: bold"><%= url.name %></span><br><%= url.description %></dt>
      <dd class="email-list"><a href="<%= url.value %>"><%= url.value %></a></dd>
      <% end %>
    </dl>
  </section>
</aside>